testlib [move] Update compiler README with required args
When attempting to use the compiler I found the documentation slightly
out-of-date: running the listed commands to compile and verify modules
and scripts resulted in an error:

```
compiler script.mvir
error: The following required arguments were not provided:
    --address <address>
```

I tried providing `--address` as instructed but encountered a different
issue:

```
compiler --address 0x02 script.mvir
thread 'main' panicked at 'Failed to compile script: Duplicate dependency module for 00000000000000000000000000000001.AccountAdministrationScripts', language/compiler/src/main.rs:144:14
```

Update the documentation with a command that works out-of-the-box. In
addition, update the output of the help text (although the
`--src-map` argument is undocumented for now).

Closes: #8596